# Generated by Django 4.0.4 on 2022-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
