# Generated by Django 4.0.4 on 2022-08-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
    ]
