# Generated by Django 4.0.4 on 2022-08-24 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 9, 55, 6, 617163, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
